### ISSUE TITLE
[v1.0.1] Bug with integration Collection2 / Simple-schema + propose inline editing of fields

### ISSUE THREAD

**Issue by geekyme** [gterrono/houston#147]
I have a collection2 collection with a schema below:

<pre>
Lines = new Meteor.Collection('lines', {
    schema: new SimpleSchema({
        author: {
            type: String
        },
        storyId: {
            type: String
        },
        submitted: {
            type: Date
        },
        text: {
            type: String,
            min: 10,
            label: 'Your entry'     
        },
        flags: {
            type: [String]
        },
        goods: {
            type: [String]
        }
    })
});

</pre>

when i updated a 'line' document, I get this error

<pre>
I20140331-22:29:19.795(8)? Exception while invoking method '_houston_lines_update' Error: failed validation: submitted: Submitted must be a Date
I20140331-22:29:19.796(8)?     at doValidate (packages/collection2/collection2.js:466)
I20140331-22:29:19.796(8)?     at Meteor.Collection.(anonymous function) [as update] (packages/collection2/collection2.js:293)
I20140331-22:29:19.796(8)?     at methods.(anonymous function) (packages/houston/server/publications.coffee:23:17)
I20140331-22:29:19.796(8)?     at maybeAuditArgumentChecks (packages/livedata/livedata_server.js:1405)
I20140331-22:29:19.796(8)?     at packages/livedata/livedata_server.js:580
I20140331-22:29:19.796(8)?     at _.extend.withValue (packages/meteor/dynamics_nodejs.js:37)
I20140331-22:29:19.796(8)?     at packages/livedata/livedata_server.js:579
I20140331-22:29:19.796(8)?     at _.extend.withValue (packages/meteor/dynamics_nodejs.js:37)
I20140331-22:29:19.796(8)?     at _.extend.protocol_handlers.method (packages/livedata/livedata_server.js:578)
I20140331-22:29:19.796(8)?     at packages/livedata/livedata_server.js:483
</pre>

I think what houston is doing is... it retrieve the database values, convert them into strings to be placed in the textarea boxes in the admin panel. That could work if I did not specify my collection2 type validation. So in this, 'submitted' fails validation since houston is passing strings to a Date field. 

I propose in-line editing in the table of documents ('home/lines'). So if I clicked the field 'text' in a selected document, I can edit the field and save, thereby triggering only a $set on that particular field i'm editing.

This library would be a good fit - http://vitalets.github.io/x-editable/

**Comment by aj07mm** [comment]
@AlexeyMK 

I had an issue of houston conflicting with simple schema:

```
TypeError: Object [object Object] has no method 'attachSchema'
    at app/lib/common.js:11:5
    at app/lib/common.js:13:3
    at /Users/aj07mm/Desktop/leilao/.meteor/local/build/programs/server/boot.js:168:10
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/aj07mm/.meteor/packages/meteor-tool/.1.0.35.1l26b8e++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at /Users/aj07mm/Desktop/leilao/.meteor/local/build/programs/server/boot.js:82:5
=> Exited with code: 8
=> Your application is crashing. Waiting for file change.
```

The same problem happened with other folks in other packages, maybe is something in houston is stubbing simple schema as i see happening with others. Just a thought.

i removed houstno:admin  from my project and now simple schema is working fine.

**Comment by AlexeyMK** [comment]
Hmm! Super interesting. If I had to guess, it's due to the
CollectionWatcher not copying things over properly. @gterrono, what do you
think?

**Comment by cubitworx** [comment]
Coming from https://github.com/aldeed/meteor-simple-schema/issues/203, I still have a problem with this on a newly installed system (Windows). If I re-add Housten after having removed it, it still doesn't work. Without Housten it works.

Since Housten is not essential to the final product I will simply remove it & move on.

Console output when trying to start Meteor...

W20150711-09:48:33.541(2)? (STDERR) TypeError: Object [object Object] has no method 'attachSchema'
W20150711-09:48:33.541(2)? (STDERR)     at app\lib\02.schemas.js:197:14
W20150711-09:48:33.541(2)? (STDERR)     at app\lib\02.schemas.js:199:3
W20150711-09:48:33.541(2)? (STDERR)     at \.meteor\local\build\programs\server\boot.js:222:10
W20150711-09:48:33.541(2)? (STDERR)     at Array.forEach (native)
W20150711-09:48:33.541(2)? (STDERR)     at Function._.each._.forEach (\.meteor\packages\meteor-tool\
1.1.3\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\underscore\underscore.js:79:11)
W20150711-09:48:33.541(2)? (STDERR)     at \.meteor\local\build\programs\server\boot.js:117:5
=> Exited with code: 8
